#!/usr/bin/python
# generated by ChatGPT
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
from zss import Node, simple_distance
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from scipy.spatial.distance import squareform
from tqdm import tqdm


# ----------------------------
# 1. Tree Loader
# ----------------------------

class CppTreeLoader:
    def __init__(self, filename):
        with open(filename, "r") as f:
            self.lines = f.readlines()
        self.index = 0

    def parse_node(self):
        if self.index >= len(self.lines):
            return None
        
        line = self.lines[self.index].strip()
        self.index += 1

        parts = line.split()
        node_type = int(parts[0])
        c = float(parts[1])
        c2 = float(parts[2])

        # IMPORTANT: usually better to ignore raw floats
        label = f"type={node_type}"
        node = Node(label)

        has_children = ((node_type <= 3) or (node_type >= 7)) and (node_type != 10)
        has_b = has_children and (node_type != 3) and (node_type != 9)

        if has_children:
            child_a = self.parse_node()
            if child_a:
                node.addkid(child_a)

            if has_b:
                child_b = self.parse_node()
                if child_b:
                    node.addkid(child_b)

        return node

    def load(self):
        return self.parse_node()


# ----------------------------
# 2. Utility: Count Nodes
# ----------------------------

def count_nodes(node):
    if node is None:
        return 0
    return 1 + sum(count_nodes(child) for child in node.children)

# ----------------------------
# 2. Load All Trees
# ----------------------------

def load_all_trees(folder, n=25000):
    trees = []
    names = []
    sizes = []

    for i in range(1, n + 1):
        try:
            filename = os.path.join(folder, f"best_{i}.txt")
            loader = CppTreeLoader(filename)
            tree = loader.load()
            trees.append(tree)
            names.append(f"best_{i}.txt")
            sizes.append(count_nodes(tree))
        except:
            break

    return trees, names, sizes

# ----------------------------
# 3. Compute Distance Matrix
# ----------------------------

def compute_distance_matrix(trees):
    n = len(trees)
    dist_matrix = np.zeros((n, n))

    for i in tqdm(range(n)):
        for j in range(i + 1, n):
            d = simple_distance(trees[i], trees[j])
            dist_matrix[i, j] = d
            dist_matrix[j, i] = d

    return dist_matrix

# ----------------------------
# 5. Clustering + Extraction
# ----------------------------

def cluster_extract(dist_matrix, names, sizes, threshold=2):
    condensed = squareform(dist_matrix)
    Z = linkage(condensed, method='average')

    # Cut tree at distance threshold
    cluster_labels = fcluster(Z, t=threshold, criterion='distance')

    # Count cluster sizes
    unique, counts = np.unique(cluster_labels, return_counts=True)
    cluster_sizes = dict(zip(unique, counts))
    print(cluster_sizes)

    # Find largest cluster
    largest_cluster_id = max(cluster_sizes, key=cluster_sizes.get)

    # Get indices of that cluster
    indices = [i for i, c in enumerate(cluster_labels) if c == largest_cluster_id]

    # Find largest tree inside that cluster
    largest_index = max(indices, key=lambda i: sizes[i])

    print(names[largest_index])

    return Z


# ----------------------------
# 4. Hierarchical Clustering
# ----------------------------

def cluster_and_plot(dist_matrix, labels):
    # Convert square matrix to condensed form
    from scipy.spatial.distance import squareform
    condensed = squareform(dist_matrix)

    Z = linkage(condensed, method='average')

    plt.figure(figsize=(16, 8))
    dendrogram(
        Z,
        labels=labels,
        leaf_rotation=90,
        leaf_font_size=6
    )
    plt.title("Hierarchical Clustering of Formula Trees")
    plt.xlabel("Models")
    plt.ylabel("Tree Edit Distance")
    plt.tight_layout()
    plt.show()


# ----------------------------
# 5. Main Execution
# ----------------------------

if __name__ == "__main__":
    plot=1
    if len(sys.argv)>=2:
        plot=int(sys.argv[1])

    folder_path = "./gp_t_series/" 
    if len(sys.argv)>=3:
        folder_path=sys.argv[2]

    trees, names, sizes = load_all_trees(folder_path)
    dist_matrix = compute_distance_matrix(trees)
    cluster_extract(dist_matrix, names, sizes, threshold=5)
    if plot==1:
        cluster_and_plot(dist_matrix, names)
